name: Test
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Retrieve pom.xml version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "maven_version=$VERSION" >> $GITHUB_ENV
          echo "VERSION from POM: $VERSION"


      - name: Parse version info from tag
        run: |
          # GITHUB_REF is like refs/tags/v2.3.5, so strip the first 11 chars
          # VERSION=${GITHUB_REF:11}
          # Parse version from tag and set environment variables
          MAJOR=$(echo "$VERSION" | cut -d . -f 1)
          MINOR=$(echo "$VERSION" | cut -d . -f 2)
          PATCH=$(echo "$VERSION" | cut -d . -f 3)
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "version_major=$MAJOR" >> $GITHUB_ENV
          echo "version_minor=$MINOR" >> $GITHUB_ENV
          echo "version_patch=$PATCH" >> $GITHUB_ENV

          # Update pom.xml to match tag version
          mvn versions:set -DnewVersion=$VERSION

      # - run: |
      #     IMG="ghcr.io/${{ github.repository }}"
      #     IMG=${IMG@L}
      #     docker build \
      #       --tag $IMG:${{ env.version }} \
      #       --tag $IMG:${{ env.version_major }}.${{ env.version_minor }}.latest \
      #       --tag $IMG:${{ env.version_major }}.latest \
      #       --tag $IMG:latest \
      #       .
      #     docker push --all-tags $IMG
